[build]
builder = "dockerfile"

[deploy]
startCommand = "./startup.sh"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
SPRING_PROFILES_ACTIVE = "railway"
