server:
  port: ${PORT:8080}   # Railway auto-injects PORT environment variable

spring:
  config:
    activate:
      on-profile: railway
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres} # Railway provides the full URL
    username: ${DATABASE_USERNAME:postgres} # Use Railway's provided variables
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, env
  endpoint:
    health:
      show-details: always
# JSONB
json:
  mapping:
    pretty-print: false

# Password Encryption
password:
  encryption:
    key: ${PASSWORD_ENCRYPTION_KEY:mytestkeyasdddds}

# JWT
jwt:
  issuer: planpro-app
  secret: ${JWT_SECRET:mySecretKey}
  expiration-ms: 86400000 # 24 hours

# RSA keys (disabled for Railway)
# rsa:
#   public-key: classpath:certs/public-key.pem
#   private-key: classpath:certs/private-key.pem

logging:
  level:
    root: info
    org.hibernate: info
    org.springframework: info
    com.planprostructure: debug
    com.zaxxer.hikari: info
    org.springframework.jdbc: info
    org.springframework.boot.autoconfigure: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

file:
  server-path: /tmp/upload-files/
  client-path: /api/v1/image
  temp-path: ${file.server-path}/temp_qr
  base-url: ${RAILWAY_STATIC_URL:https://planpro-api-production.up.railway.app}${file.client-path}
  base-image-url: ${RAILWAY_STATIC_URL:https://planpro-api-production.up.railway.app}

telegram-setting:
  enable: ${TELEGRAM_BOT_ENABLE:false}
  base-url: https://api.telegram.org
  username: ${TELEGRAM_BOT_USERNAME:planproapp_bot}
  access-token: "${TELEGRAM_BOT_TOKEN:your-token-here}"
  bot-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}
  share-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    filter: true
    try-it-out-enabled: false
    doc-expansion: none
    default-models-expand-depth: 1
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
