server:
  port: ${PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # Use Railway's PostgreSQL environment variables
    url: ${Postgres.DATABASE_URL}
    username: ${Postgres.POSTGRES_USER}
    password: ${Postgres.POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        # Add connection pool debugging
        connection:
          provider_disables_autocommit: true
      javax:
        persistence:
          schema-generation:
            database:
              action: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# JSONB Configuration
json:
  mapping:
    pretty-print: false

# Password Encryption
password:
  encryption:
    key: ${PASSWORD_ENCRYPTION_KEY:mytestkeyasdddds}

# Application URLs
web-url: ${RAILWAY_STATIC_URL:https://your-app-name.railway.app}

# JWT Configuration
jwt:
  expiration: 86400000 # 24 hours in milliseconds
  issuer: planpro-app
  secret: ${JWT_SECRET:mySecretKey}
  expirationMs: 86400000 # 24 hours in milliseconds

# RSA Keys Configuration
rsa:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem

# Logging Configuration
logging:
  file:
    name: planpro-app.log
  level:
    root: info
    org.hibernate: info
    org.springframework: info
    com.planprostructure: info
    com.zaxxer.hikari: debug
    org.springframework.jdbc: debug

# File Storage Configuration
file:
  server-path: /tmp/upload-files/
  client-path: /api/v1/image
  temp-path: ${file.server-path}/temp_qr
  base-url: ${RAILWAY_STATIC_URL:https://your-app-name.railway.app}${file.client-path}
  base-image-url: ${RAILWAY_STATIC_URL:https://your-app-name.railway.app}

# Telegram Configuration
telegram-setting:
  enable: ${TELEGRAM_BOT_ENABLE:false}
  base-url: https://api.telegram.org
  username: ${TELEGRAM_BOT_USERNAME:planproapp_bot}
  access-token: ${TELEGRAM_BOT_TOKEN:7845816657:AAEJxT5tVXW88cDYELYli2ttY5glQsJQq7o}
  bot-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}
  share-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}
  
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    filter: true
    try-it-out-enabled: false
    doc-expansion: none
    default-models-expand-depth: 1
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json 