server:
  port: 9090
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5433/planpro_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
password:
  encryption:
    key: mytestkeyasdddds
web-url: http://localhost:3001

# JWT Configuration for RSA Keys
jwt:
  expiration: 86400000 # 24 hours in milliseconds
  issuer: planpro-app
  secret: mySecretKey
  expirationMs: 86400000 # 24 hours in milliseconds

rsa:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem

logging:
  level:
    org:
      springframework:
        security: DEBUG