server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planpro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration for RSA Keys
jwt:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem
  expiration: 86400000 # 24 hours in milliseconds
  issuer: planpro-app

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.planprostructure: DEBUG