server:
  port: ${PORT:8080}   # Railway auto-injects PORT environment variable

spring:
  datasource:
    hikari:
      fail-fast: false
      maximum-pool-size: 2   # small pool for Railway
      minimum-idle: 0
      connection-timeout: 10000
      idle-timeout: 300000        # 5m
      max-lifetime: 600000        # 10m
      keepalive-time: 60000       # 1m
      leak-detection-threshold: 30000
      connection-test-query: SELECT 1
      validation-timeout: 3000
      register-mbeans: false
      initialization-fail-timeout: 10000

  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
    banner-mode: console
    web-application-type: servlet

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 5
          batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        order_updates: true
        batch_fetch_style: DYNAMIC
        cache:
          use_second_level_cache: false
          use_query_cache: false
      javax:
        persistence:
          schema-generation:
            database:
              action: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  server:
    port: ${MANAGEMENT_PORT:${PORT:8080}}   # ✅ Ensures integer; can use same as PORT
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      group:
        db:
          include: db
          show-details: when-authorized

# JSONB
json:
  mapping:
    pretty-print: false

# Password Encryption
password:
  encryption:
    key: ${PASSWORD_ENCRYPTION_KEY:mytestkeyasdddds}

# JWT
jwt:
  issuer: planpro-app
  secret: ${JWT_SECRET:mySecretKey}
  expiration-ms: 86400000 # 24 hours

# RSA keys (disabled for Railway)
# rsa:
#   public-key: classpath:certs/public-key.pem
#   private-key: classpath:certs/private-key.pem

logging:
  level:
    root: info
    org.hibernate: info
    org.springframework: info
    com.planprostructure: debug
    com.zaxxer.hikari: info
    org.springframework.jdbc: info
    org.springframework.boot.autoconfigure: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

file:
  server-path: /tmp/upload-files/
  client-path: /api/v1/image
  temp-path: ${file.server-path}/temp_qr
  base-url: ${RAILWAY_PUBLIC_DOMAIN:https://planpro-api-production.up.railway.app}${file.client-path}
  base-image-url: ${RAILWAY_PUBLIC_DOMAIN:https://planpro-api-production.up.railway.app}

telegram-setting:
  enable: ${TELEGRAM_BOT_ENABLE:false}
  base-url: https://api.telegram.org
  username: ${TELEGRAM_BOT_USERNAME:planproapp_bot}
  access-token: "${TELEGRAM_BOT_TOKEN:your-token-here}"
  bot-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}
  share-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    filter: true
    try-it-out-enabled: false
    doc-expansion: none
    default-models-expand-depth: 1
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
