spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: quartz
  main:
    allow-circular-references: true
jwt:
  expiration: 2h

rsa:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem