management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    info:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    defaults:
      enabled: true
