server:
  port: ${PORT:8080}

spring:
  datasource:
    # Railway PostgreSQL Configuration with SSL
    url: ${DATABASE_URL:jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory&tcpKeepAlive=true&socketTimeout=30&connectTimeout=30}
    username: ${PROD_DB_USERNAME:postgres}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3  # Reduced from 10 to 3
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      keepalive-time: 30000
      register-mbeans: false  # Disable MBean registration
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 10  # Reduced from 20
          batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        order_updates: true
        batch_fetch_style: DYNAMIC
      javax:
        persistence:
          schema-generation:
            database:
              action: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

json:
  mapping:
    pretty-print: false

password:
  encryption:
    key: ${PASSWORD_ENCRYPTION_KEY:mytestkeyasdddds}

jwt:
  issuer: planpro-app
  secret: ${JWT_SECRET:mySecretKey}
  expiration-ms: 86400000 # 24 hours

rsa:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem

logging:
  level:
    root: warn  # Changed from info to warn
    org.hibernate: warn  # Changed from info to warn
    org.springframework: warn  # Changed from info to warn
    com.planprostructure: info
    com.zaxxer.hikari: warn  # Changed from debug to warn
    org.springframework.jdbc: warn  # Changed from debug to warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Simplified log format

file:
  server-path: /tmp/upload-files/
  client-path: /api/v1/image
  temp-path: ${file.server-path}/temp_qr
  base-url: ${RAILWAY_STATIC_URL:https://planpro-api-production.up.railway.app}${file.client-path}
  base-image-url: ${RAILWAY_STATIC_URL:https://planpro-api-production.up.railway.app}

telegram-setting:
  enable: ${TELEGRAM_BOT_ENABLE:false}
  base-url: https://api.telegram.org
  username: ${TELEGRAM_BOT_USERNAME:planproapp_bot}
  access-token: "${TELEGRAM_BOT_TOKEN:your-token-here}"
  bot-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}
  share-url: https://t.me/${TELEGRAM_BOT_USERNAME:planproapp_bot}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    filter: true
    try-it-out-enabled: false
    doc-expansion: none
    default-models-expand-depth: 1
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
